### PR TITLE
Fix Android browser search enter

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
On Android browsers, currently, one cannot click "enter" to search for the given prefix.
This is due to the mobile cards view of the table, which introduces the dropdown menu which in turn allows one to change the order within the table.
When pressing "enter" whilst the search bar is focussed, the focus switches to this order dropdown menu instead of searching.
To fix this, I set `enterkeyhint="search"`. This even switches the "enter" button on virtual keyboards to a magnifying glass!

Additionally, I switched from `@keyup.enter` to `@keydown.enter`, which is also what other big search engines do (such as Google).
I think this is somewhat nicer, but I can also revert this particular change if you want :)

### CODE REVIEW

**Comment by ThexXTURBOXx** [comment]
Oops, didn't mean to only draft this PR

**Review by qoomon — APPROVED** [review]

**Comment by qoomon** [comment]
Should be fixed in version 3.0.2

**Comment by qoomon** [comment]
Thanks for the PR

**Comment by ThexXTURBOXx** [comment]
You're welcome, and also thank you very much! :)

**Pull request merged**
